webApps_django-u12/vydli/movies/urls.py
from django.urls import path

from . import views #It is better to do it in this way because
                    #someone can use a different path

app_name = 'movies'

urlpatterns = [ #This is the URL configuration
    path('', views.index,name='index'),
    path('<int:movie_id>',views.detail,name='detail')
]

webApps_django-u12/vydli/vidly/urls.py
from django.contrib import admin
from django.urls import path, include
from api.models import MovieResource
from . import views

movie_resource = MovieResource()

urlpatterns = [
    path('',views.home),
    path('admin/', admin.site.urls),
    path('movies/',include('movies.urls')),
    path('api/',include(movie_resource.urls))
]

webApps_django-u12/vydli/api/models.py
from django.db import models
from tastypie.resources import ModelResource
from movies.models import Movie

class MovieResource(ModelResource):
    class Meta:
        queryset = Movie.objects.all()
        resource_name = 'movies'
        excludes = ['date_created']

webApps_django-u12/vydli/movies/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Genre(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name
    
class Movie(models.Model):
    title = models.CharField(max_length=255)
    release_year = models.IntegerField()
    number_in_stock = models.IntegerField()
    daily_rate = models.FloatField()
    Genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
    date_created = models.DateTimeField(default=timezone.now)

webApps_django-u12/vydli/api/views.py
from django.shortcuts import render

# Create your views here.

webApps_django-u12/vydli/movies/views.py
from django.http import HttpResponse, Http404
from django.shortcuts import render, get_object_or_404
from .models import Movie

def index(request):
    movies = Movie.objects.all()
    return render(request=request,template_name='movies/index.html',context={'movies':movies})

def detail(request,movie_id):
    movie = get_object_or_404(Movie,pk=movie_id)
    return render(request=request,template_name='movies/detail.html',context={'movie':movie})

webApps_django-u12/vydli/vidly/views.py
from django.shortcuts import render

def home(request):
    return render(request,'home.html')

webApps_django-u12/vydli/movies/templates/movies/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Vidly</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
    {% block content %}
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

webApps_django-u12/vydli/movies/templates/movies/detail.html
{% extends "base.html" %}

{% block content %}
    <dl>
        <dt>Title</dt>
        <dd>{{movie.title}}</dd>
        <dt>Genre</dt>
        <dd>{{movie.Genre}}</dd>
        <dt>Stock</dt>
        <dd>{{movie.number_in_stock}}</dd>
    </dl>
{% endblock  %}

webApps_django-u12/vydli/movies/templates/movies/index.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>This is my movie app</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->

        {% extends "base.html" %}

        {% block content %}

        <table class="table table-bordered">
            <thread>
                <tr>
                    <th>Title</th>
                    <th>Genre</th>
                    <th>Stock</th>
                    <th>Daily Rate</th>
                </tr>
            </thread>
            <tbody>
                {% for movie in movies %}
                <tr>
                    <td>
                        <a href="{% url 'movies:detail' movie.id%}">{{movie.title}}</a>
                    </td>
                    <td>{{movie.Genre}}</td>
                    <td>{{movie.number_in_stock}}</td>
                    <td>{{movie.daily_rate}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% endblock%}

        <script src="" async defer></script>
    </body>
</html>

webApps_django-u12/vydli/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Vidly</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Vidly</a>
      </div>
    </nav>

    <main class="container">
      {% block content %}
      {% endblock %}
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

webApps_django-u12/vydli/templates/home.html
{% extends "base.html"%}

{% block content %}
    <a href="{%url 'movies:index'%}">Movies</a>
{% endblock%}